### ISSUE TITLE
Running it on Raspbian it started to produce this error a few weeks ago

### ISSUE THREAD

**Issue by gkovacsp** [pv8/noipy#128]
Used to work well, I'm not sure what broke it.
OS: Raspbian GNU/Linux 10 (buster)
HW: Raspberry 4

Command line:
`/usr/local/bin/noipy -u xxxxxx -p xxxxxx -n xxxxxx.ddns.net --provider noip`

Result:
> == noipy DDNS updater tool v1.5.2 ==
Traceback (most recent call last):
  File "/usr/local/bin/noipy", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/noipy/main.py", line 168, in main
    result = execute_update(args)
  File "/usr/local/lib/python2.7/dist-packages/noipy/main.py", line 111, in execute_update
    ip_address = args.ip if args.ip else utils.get_ip()
  File "/usr/local/lib/python2.7/dist-packages/noipy/utils.py", line 29, in get_ip
    ip, _ = r.json()['origin'].split(',')
ValueError: need more than 1 value to unpack

**Comment by pv8** [comment]
@gkovacsp, thanks for reporting the issue. The service used to retrieve the current machine's IP (https://httpbin.org/) has changed its response. Patch coming soon.

**Comment by pv8** [comment]
Closed by #130
