### ISSUE TITLE
Tests failing with Python 3.2

### ISSUE THREAD

**Issue by pv8** [pv8/noipy#17]
Because **virtualenv** has [dropped support for Python 3.2 on version 14.0.0](https://virtualenv.pypa.io/en/latest/changes.html#id9), **noipy** building has [been falling](https://travis-ci.org/pv8/noipy/jobs/123505011#L217):
```sh
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>
py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/p...x/py32/bin/python3.2 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /opt/python/3.2.5/bin/python3.2
ERROR: InvocationError: /home/travis/virtualenv/python2.7.9/bin/python -m virtualenv --python /opt/python/3.2.5/bin/python3.2 py32 (see /home/travis/build/pv8/noipy/.tox/py32/log/py32-0.log)
___________________________________ summary ____________________________________
ERROR:   py32: InvocationError: /home/travis/virtualenv/python2.7.9/bin/python -m virtualenv --python /opt/python/3.2.5/bin/python3.2 py32 (see /home/travis/build/pv8/noipy/.tox/py32/log/py32-0.log)
The command "tox -e $TOXENV" exited with 1.
store build cache
0.00s
10.77schange detected:
(dev).tmpl
/home/travis/build/pv8/noipy/.tox/dist/noipy-1.4.4.zip
/home/travis/build/pv8/noipy/.tox/log/tox-0.log
/home/travis/build/pv8/noipy/.tox/py27/bin/activate
/home/travis/build/pv8/noipy/.tox/py27/bin/activate.csh
/home/travis/build/pv8/noipy/.tox/py27/bin/activate.fish
/home/travis/build/pv8/noipy/.tox/py27/bin/activate_this.py
/home/travis/build/pv8/noipy/.tox/py27/bin/coverage
/home/travis/build/pv8/noipy/.tox/py27/bin/coverage2
/home/travis/build/pv8/noipy/.tox/py27/bin/coverage-2.7
/home/travis/build/pv8/noipy/.tox/py27/bin/easy_install
/home/travis/build/pv8/noipy/.tox/py27/bin/easy_install-2.7
/home/travis/build/pv8/noipy/.tox/py27/bin/noipy
/home/travis/build/pv8/noipy/.tox/py27/bin/pip
/home/travis/build/pv8/noipy/.tox/py27/bin/pip2
/home/travis/build/pv8/noipy/.tox/py27/bin/pip2.7
/home/travis/build/pv8/noipy/.tox/py27/bin/python
/home/travis/build/pv8/noipy/.tox/py27/bin/python2
/home/travis/build/pv8/noipy/.tox/py27/bin/python2.7
/home/travis/build/pv8/noipy/.tox/py2
...
changes detected, packing new archive
.
uploading archive
Done. Your build exited with 1.
```

**Workaround it** or **drop support to Python 3.2 as well**?

**Comment by pv8** [comment]
According to [PEP 392](https://www.python.org/dev/peps/pep-0392), Python 3.2 is outside of official support [since February 2016](https://www.python.org/dev/peps/pep-0392/#lifespan).

**Comment by pv8** [comment]
According to [PEP 392](https://www.python.org/dev/peps/pep-0392), Python 3.2 is outside of official support [since February 2016](https://www.python.org/dev/peps/pep-0392/#lifespan).
